### ISSUE TITLE
Adding configuration-pathfile for task command

### ISSUE THREAD

**Issue by dragonito** [DavidBadura/Taskwarrior#21]
Adding configuration-pathfile for task command:

On some environments task is not available in global path, so it would be great to make it optional configurable

**Comment by tolry** [comment]
In taskwarrior-lib this should probably just be an argument to the taskwarrior class' constructor, with a default of 'task'. Afterwards this can be made configurable in doThings.

**Comment by DavidBadura** [comment]
https://github.com/DavidBadura/Taskwarrior/commit/c96bd153a45fd6cc75f0e6667cf3bda4a86eb4f2
