### ISSUE TITLE
bug "someday" tag

### ISSUE THREAD

**Issue by DavidBadura** [DavidBadura/Taskwarrior#25]
if you add a tag named `someday` it will be converted to `2038-01-18T00:00:00` in taskwarrior.

**Comment by tolry** [comment]
Some background info: the cause for this being the possibility in taskwarrior to set a task to some day in the distant future by using "task 123 mod due:someday", resulting in taskwarrior translating "someday" to a unix epoch timestamp with UINT_MAX as value => 2038

**Comment by DavidBadura** [comment]
will be fixed in Taskwarrior 2.4.5 https://bug.tasktools.org/browse/TW-1555 & https://bug.tasktools.org/browse/TW-1627
